Make `Task` a subclass of `Struct`.
Fixe error:

    AttributeError: 'RetryableTask' object has no attribute 'get'

caused by passing instances of `RetryableTask` instead of instances of
`Application` to `SessionBasedScript._save_session`.