Fix "AttributeError: 'ShellcmdLrms' object has no attribute '_make_remote_and_local_path_pair'"
Function was moved and renamed but apparently a line escaped my quick `grep` search...

Fixes #627