Fix tests in `gc3libs/tests/test_utils.py` on Py3.
Tests would fail with:

    ModuleNotFoundError: No module named '__builtin__'

because the `__builtin__` module has been renamed to `builtins` in
Python 3.