install.py: Require the `make` command to be present.
If it's not available, installation of the `pynacl` package will fail
with a mysterious last line:

    error: No such file or directory