Fix "ImportError: cannot import name same_file".
In commit SVN r2247, we forgot to change all occurrences of
`gc3libs.utils.same_file` to `gc3libs.utils.samefile`.

  modified:   gc3libs/backends/shellcmd.py
  modified:   gc3libs/utils.py