Fix "AttributeError: 'UrlKeyDict' object has no attribute '_force_abs'"
This issue would pop up when restoring saved jobs from disk, due to
the special way `pickle` handles `dict` objects.

Example traceback:

    Traceback (most recent call last):
    File ".../gc3pie/gc3libs/persistence/filesystem.py", line 126, in load
      obj = self._load_from_file(source)
    File ".../gc3pie/gc3libs/persistence/filesystem.py", line 104, in _load_from_file
      obj = unpickler.load()
    File ".../gc3pie/gc3libs/url.py", line 504, in __setitem__
      dict.__setitem__(self, Url(key, self._force_abs), value)
    AttributeError: 'UrlKeyDict' object has no attribute '_force_abs'